export const SET_LOADING = '@SET_LOADING';
export const SET_IS_ONLINE = '@SET_IS_ONLINE';
export const SET_REFRESHING = '@SET_REFRESHING';

// Akun
export const SET_AKUN_LOADING = '@SET_AKUN_LOADING';
export const SET_AKUN_ERROR = '@SET_AKUN_ERROR';
export const SET_AKUN_SUCCESS = '@SET_AKUN_SUCCESS';

// update akun
export const SET_UPDATE_AKUN_LOADING = '@SET_UPDATE_AKUN_LOADING';
export const SET_UPDATE_AKUN_ERROR = '@SET_UPDATE_AKUN_ERROR';
export const SET_UPDATE_AKUN_SUCCESS = '@SET_UPDATE_AKUN_SUCCESS';

//Auth Login
export const SET_LOGIN_LOADING = '@SET_LOGIN_LOADING';
export const SET_LOGIN_ERROR = '@SET_LOGIN_ERROR';
export const SET_LOGIN_SUCCESS = '@SET_LOGIN_SUCCESS';
export const SET_ROLE = '@SET_ROLE';

//Auth ForgetPass
export const SET_FORGETPASS_LOADING = '@SET_FORGETPASS_LOADING';
export const SET_FORGETPASS_ERROR = '@SET_FORGETPASS_ERROR';
export const SET_FORGETPASS_SUCCESS = '@SET_FORGETPASS_SUCCESS';

//Auth signOut
export const SET_SIGNOUT_LOADING = '@SET_SIGNOUT_LOADING';
export const SET_SIGNOUT_ERROR = '@SET_SIGNOUT_ERROR';
export const SET_SIGNOUT_SUCCESS = '@SET_SIGNOUT_SUCCESS';

//Chat getAllUser
export const SET_GETALLUSER_LOADING = '@SET_GETALLUSER_LOADING';
export const SET_GETALLUSER_ERROR = '@SET_GETALLUSER_ERROR';
export const SET_GETALLUSER_SUCCESS = '@SET_GETALLUSER_SUCCESS';

//Chat getChat
export const SET_GETCHAT_LOADING = '@SET_GETCHAT_LOADING';
export const SET_GETCHAT_ERROR = '@SET_GETCHAT_ERROR';
export const SET_GETCHAT_SUCCESS = '@SET_GETCHAT_SUCCESS';

//Chat searchUser
export const SET_SEARCHUSER_LOADING = '@SET_SEARCHUSER_LOADING';
export const SET_SEARCHUSER_ERROR = '@SET_SEARCHUSER_ERROR';
export const SET_SEARCHUSER_SUCCESS = '@SET_SEARCHUSER_SUCCESS';

//Chat Create_Chat_List
export const CREATE_CHAT_LIST_LOADING = '@CREATE_CHAT_LIST_LOADING';
export const CREATE_CHAT_LIST_ERROR = '@CREATE_CHAT_LIST_ERROR';
export const CREATE_CHAT_LIST_SUCCESS = '@CREATE_CHAT_LIST_SUCCESS';

//chat GET_CHAT_LIST
export const GET_CHAT_LIST_LOADING = '@GET_CHAT_LIST_LOADING';
export const GET_CHAT_LIST_ERROR = '@GET_CHAT_LIST_ERROR';
export const GET_CHAT_LIST_SUCCESS = '@GET_CHAT_LIST_SUCCESS';

//Request
export const SET_REQUEST_LOADING = '@SET_REQUEST_LOADING';
export const SET_REQUEST_ERROR = '@SET_REQUEST_ERROR';
export const SET_REQUEST_SUCCESS = '@SET_REQUEST_SUCCESS';

// getRequest
export const GET_REQUEST_LOADING = '@GET_REQUEST_LOADING';
export const GET_REQUEST_ERROR = '@GET_REQUEST_ERROR';
export const GET_REQUEST_SUCCESS = '@GET_REQUEST_SUCCESS';

// update request
export const UPDATE_REQUEST_LOADING = '@UPDATE_REQUEST_LOADING';
export const UPDATE_REQUEST_ERROR = '@UPDATE_REQUEST_ERROR';
export const UPDATE_REQUEST_SUCCESS = '@UPDATE_REQUEST_SUCCESS';

// delete request
export const DELETE_REQUEST_LOADING = '@DELETE_REQUEST_LOADING';
export const DELETE_REQUEST_ERROR = '@DELETE_REQUEST_ERROR';
export const DELETE_REQUEST_SUCCESS = '@DELETE_REQUEST_SUCCESS';

// setIsRequestPending
export const SET_IS_REQUEST_PENDING = '@SET_IS_REQUEST_PENDING';

// Request countRequestNotif

export const SET_COUNT_REQUESt = '@SET_COUNT_REQUESt';

//Notif getNotif
export const SET_GETNOTIF_LOADING = '@SET_GETNOTIF_LOADING';
export const SET_GETNOTIF_ERROR = '@SET_GETNOTIF_ERROR';
export const SET_GETNOTIF_SUCCESS = '@SET_GETNOTIF_SUCCESS';

//Notif updateNotif
export const UPDATE_NOTIF_LOADING = '@UPDATE_NOTIF_LOADING';
export const UPDATE_NOTIF_ERROR = '@UPDATE_NOTIF_ERROR';
export const UPDATE_NOTIF_SUCCESS = '@UPDATE_NOTIF_SUCCESS';

//Notif setNotif
export const SET_SETNOTIF_LOADING = '@SET_SETNOTIF_LOADING';
export const SET_SETNOTIF_ERROR = '@SET_SETNOTIF_ERROR';
export const SET_SETNOTIF_SUCCESS = '@SET_SETNOTIF_SUCCESS';

//Notif countNotification
export const SET_NOTIFICATION_TOTAL = '@SET_NOTIFICATION_TOTAL';

//Location getLocation
export const GET_LOCATION_LOADING = '@GET_LOCATION_LOADING';
export const GET_LOCATION_ERROR = '@GET_LOCATION_ERROR';
export const GET_LOCATION_SUCCESS = '@GET_LOCATION_SUCCESS';

// presence getPresence
export const GET_PRESENCE_LOADING = '@GET_PRESENCE_LOADING';
export const GET_PRESENCE_ERROR = '@GET_PRESENCE_ERROR';
export const GET_PRESENCE_SUCCESS = '@GET_PRESENCE_SUCCESS';

// presence setPresence
export const SET_PRESENCE = '@SET_PRESENCE';

// presence presence
export const SET_PRESENCE_LOADING = '@SET_PRESENCE_LOADING';
export const SET_PRESENCE_ERROR = '@SET_PRESENCE_ERROR';
export const SET_PRESENCE_SUCCESS = '@SET_PRESENCE_SUCCESS';
