export const SET_LOADING = '@SET_LOADING';

// Akun
export const SET_AKUN_LOADING = '@SET_AKUN_LOADING';
export const SET_AKUN_ERROR = '@SET_AKUN_ERROR';
export const SET_AKUN_SUCCESS = '@SET_AKUN_SUCCESS';

// update akun
export const SET_UPDATE_AKUN_LOADING = '@SET_UPDATE_AKUN_LOADING';
export const SET_UPDATE_AKUN_ERROR = '@SET_UPDATE_AKUN_ERROR';
export const SET_UPDATE_AKUN_SUCCESS = '@SET_UPDATE_AKUN_SUCCESS';

//Auth Login
export const SET_LOGIN_LOADING = '@SET_LOGIN_LOADING';
export const SET_LOGIN_ERROR = '@SET_LOGIN_ERROR';
export const SET_LOGIN_SUCCESS = '@SET_LOGIN_SUCCESS';

//Auth ForgetPass
export const SET_FORGETPASS_LOADING = '@SET_FORGETPASS_LOADING';
export const SET_FORGETPASS_ERROR = '@SET_FORGETPASS_ERROR';
export const SET_FORGETPASS_SUCCESS = '@SET_FORGETPASS_SUCCESS';

//Auth signOut
export const SET_SIGNOUT_LOADING = '@SET_SIGNOUT_LOADING';
export const SET_SIGNOUT_ERROR = '@SET_SIGNOUT_ERROR';
export const SET_SIGNOUT_SUCCESS = '@SET_SIGNOUT_SUCCESS';

//Chat getAllUser
export const SET_GETALLUSER_LOADING = '@SET_GETALLUSER_LOADING';
export const SET_GETALLUSER_ERROR = '@SET_GETALLUSER_ERROR';
export const SET_GETALLUSER_SUCCESS = '@SET_GETALLUSER_SUCCESS';

//Chat getChat
export const SET_GETCHAT_LOADING = '@SET_GETCHAT_LOADING';
export const SET_GETCHAT_ERROR = '@SET_GETCHAT_ERROR';
export const SET_GETCHAT_SUCCESS = '@SET_GETCHAT_SUCCESS';

//Chat searchUser
export const SET_SEARCHUSER_LOADING = '@SET_SEARCHUSER_LOADING';
export const SET_SEARCHUSER_ERROR = '@SET_SEARCHUSER_ERROR';
export const SET_SEARCHUSER_SUCCESS = '@SET_SEARCHUSER_SUCCESS';
