import {
  REACT_PROJECT_NUMBER,
  REACT_FIREBASE_URL,
  REACT_PROJECT_ID,
  REACT_STORAGE_BUCKET,
} from '@env';

export default {
  REACT_PROJECT_NUMBER,
  REACT_FIREBASE_URL,
  REACT_PROJECT_ID,
  REACT_STORAGE_BUCKET,
};
